[project]
name = "slack-mcp"
version = "0.1.0"
description = "S.T.A Track Python Assignment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.5.1",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
